[project]
name = "vagabondengineer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "wagtail>=7.0",
]

[dependency-groups]
dev = [
    "djlint>=1.36.4",
]
